### ISSUE TITLE
Determining an account's type

### ISSUE THREAD

**Issue by ChrisRzech** [B-Minus-Programmers/jojibrush#12]
As a developer, I want to be able to determine the account type of a users ID to give the user certain features.

# Tasks:
 - Traverse through a user data file
 - If the user ID matches the wanted user ID, load in the account type from the file into a string
 - Convert string into a valid data type for representing account types

# Tests:
 - Given a registered user ID, determine the account type
 - Given a unregistered user ID (random ID), throw an exception

**Priority:** Low

**Comment by dacruz21** [comment]
Can we expand this to the entire login process? i.e. rename to "Determine if a user is an admin or a guest", and add a little bit of detail regarding how we store this, how we can check if a user is an admin-- this will be much more than just a dialog box.
