### ISSUE TITLE
Producing Shape Listing Reports

### ISSUE THREAD

**Issue by BenjiBoy926** [B-Minus-Programmers/jojibrush#14]
As a guest or administrator, I can produce a shape listing report

# Tasks:
 - As a guest or administrator, I can produce a shape listing report sorted by shape id's
- As a guest or administrator, I can produce a shape listing report sorted by shape areas
NOTE: shapes without areas, such as lines, are excluded from this report
- As a guest or administrator, I can produce a shape listing report sorted by shape perimeters
NOTE: the "length" of a line counts as its "perimeter"

# Tests:
 - Verify that the sorting is accurate
- Verify that lines and polylines are excluded from the report based on shape area

**Priority:** High

**Comment by dacruz21** [comment]
needs estimate but looks good!
