### ISSUE TITLE
jojibrush splash screen 

### ISSUE THREAD

**Issue by jthomas2234** [B-Minus-Programmers/jojibrush#17]
As a developer I want to create a slash screen for the 2D modeler application that will display the logo for the group project of (joji). 

# Tasks:
 - implement the logo from the group project for the loading screen 
- logo should spin when the modeler is being loaded
- loading screen should have a time-out of 1.5  seconds while loading modeler

# Tests:
 - logo animation spins in a clockwise direction
- loading screen time-out is as expected (1.5s) 
- transitions to modeler without any interruption

Priority: Low

**Comment by dacruz21** [comment]
Story should be from the perspective of the user -- this doesn't really affect development of the program. Also might be worth defining how long the window is open, how it's laid out, etc. I don't think we have much data to load, so we should probably set a fixed length of time for the window to appear

**Comment by jthomas2234** [comment]
let me know if this is ok, or if more needs to be added

**Comment by dacruz21** [comment]
That timeout is way too long IMO, how about 1.5 sec and no spinning?
