### ISSUE TITLE
Selection Sort Algorithm

### ISSUE THREAD

**Issue by grantcoz** [B-Minus-Programmers/jojibrush#18]
As a user, I want to be able to sort my vector of shapes via a function called Selection_sort

# Tasks:

- Create a function for sorting the vector

- The function must be templated

- the parameter for the function must be a function pointer

- The function must be sorted by id or custom comparison functions

# Tests:
 - Test to see if that each shape is sorted properly via id or custom comparison functions

- Test to if the sort goes out of the scope of the vector

Priority: High

**Comment by dacruz21** [comment]
will start once vector diff is landed
