### ISSUE TITLE
Implement geometric shapes

### ISSUE THREAD

**Issue by dacruz21** [B-Minus-Programmers/jojibrush#22]
As a user, I want to have access to basic geometric shapes (such as rectangles and circles) to more easily create art. I also want access to a "donut" shape (hollow circle with thick outline) so that I can create propaganda to convince Joji to bring donuts for the team.

# Tasks:
 - Create abstract class for geometric shapes, with area and perimeter properties
 - Create Rectangle class extending from GeometricShape
 - Create Ellipse class extending from GeometricShape
 - Create Donut class extending from GeometricShape
 - Define area and perimeter methods for all geometric shapes
 - Integrate these shapes with the palette

# Tests:
 - Place one of each shape on a canvas
 - Ensure the shapes are rendered correctly
 - Ensure the shapes can be saved to a file in the correct format
 - Produce a report of all shapes sorted by area and perimeter and ensure correct values for both

**Priority:** Medium

**Comment by ChrisRzech** [comment]
This issue needs to be worked on ASAP. The "donut" shape has one of the highest priorities right now.
