### ISSUE TITLE
Small Menu For Text Boxes

### ISSUE THREAD

**Issue by AAE1997** [B-Minus-Programmers/jojibrush#29]
As a User I want to select a certain style of text (ex. Times New Roman), access a library of shapes, and look up the properties of the file

# Tasks:
 - Create text boxs to type text with a small box menu to select font, color, bold, italized, etc.
 - Create a selection of text fonts (can choose how many you want).
 - Create a properties class that will display the contents of the file.

# Tests:
 - When displaying the text fonts make sure the texts are stylized in their respected font.
 - Assure the menu is displayed when cursor is in the text box.

Priority: Medium

**Comment by dacruz21** [comment]
> access a library of shapes

Seems like a different task entirely

> look up the properties of the file

Like brush properties? This could be a little more clear -- properties for text should just be font, font size, maybe style?

> Create a library of shapes using certain shape classes

Scope this down to just text shapes, we already have geo and lines

> Create a properties class that will display the contents of the file

Not really sure what this means? Are you talking about saving font style and size to the file?

> Make sure the properties of the file are displaying the date created, accessed, file type, etc.

what?

> Assure the user sees the shapes' names displayed.

Did you mean IDs?

**Comment by AAE1997** [comment]
The last task is optional, don't worry about that one.

For properties, can be for text & font style. I'm a little confused about "text shapes"

I was talking about the content of the file's properties like file type, date accessed, date created, file size, dimensions, etc.

I'll clarify the rest in lab.

**Comment by dacruz21** [comment]
> I was talking about the content of the file's properties like file type, date accessed, date created, file size, dimensions, etc.

I still have no idea what this has to do with text shapes

**Comment by AAE1997** [comment]
You said "Scope this down to just **text shapes**, we already have geo and lines"
->Create a properties class that will display the contents of the file

**Comment by dacruz21** [comment]
Right, see #22 and #26. Can you scope down the story and tasks for the text shape only? We already have polygons, rectangles, circles, etc. in #22 and freehand lines, straight lines in #26. All that's left is the text shape.

I still think properties class should be split into another task (and I still don't know exactly why we need it)

**Comment by AAE1997** [comment]
Alright. What about the fonts?

**Comment by dacruz21** [comment]
Fonts seems like it's in scope for this issue, that's fine. Please also add the estimate to Waffle for this ticket and your last one.

**Comment by AAE1997** [comment]
![frame-clipart-invitation-12](https://user-images.githubusercontent.com/44478539/48086570-0ccd2780-e1b2-11e8-9987-1d7bc7dc0b6c.jpg)


Text shapes like these?
