### ISSUE TITLE
Set up QWidget Rendering Area

### ISSUE THREAD

**Issue by dacruz21** [B-Minus-Programmers/jojibrush#3]
As a user, I want to be greeted by a blank canvas, so that I can start drawing my image

Tasks:
 - Set up canvas class, extending QWidget
 - Make this view the default view of the application
 - Canvas should store Shapes and render them to the screen
 - Canvas should display shape IDs above each shape

Tests:
 - Make sure canvas appears when the application is opened
 - Manually create a shape and ensure it is rendered in the correct position

Priority: High

**Comment by dacruz21** [comment]
status update -- made some good progress so far, blocked until abstract shape diff is landed

**Comment by ChrisRzech** [comment]
Status update:
Abstract shape is now created, get working bud
