### ISSUE TITLE
Basic Log in Screen

### ISSUE THREAD

**Issue by jthomas2234** [B-Minus-Programmers/jojibrush#30]
As a user I want to have a layout of a basic log-in screen which takes in a username and password (more will be added to this later)

# Tasks:
 - create a window that requires a username/password

# Tests:
 - make sure window for log-in size fits the screen
 -  see if password and username fits in the required fields 

**Priority:** Low

**Comment by AAE1997** [comment]
What kind of account are we going to use (YAHOO!, Microsoft, G-Mail, etc.)?

**Comment by jthomas2234** [comment]
I'm unsure what this pertains to this exactly? This issue was just for creating a simple layout for our login process to the modeler. Just a box dialog that will allow someone to input their username and password which we will later verify. Unless theres more to what you mean let me know more specifically, thanks.

**Comment by ChrisRzech** [comment]
We have decided that whenever an admin's username is typed in, the login screen logo's eyes will turn red. NANI!?
