### ISSUE TITLE
This needs to be a private repo

### ISSUE THREAD

**Issue by Autofire** [B-Minus-Programmers/jojibrush#40]
As a class project, this needs to be private.

I'm only telling you this because your group could get in serious trouble for academic dishonesty. Another group could easy come in and grab your project.

(FYI I found out about this repo because Github recommended it to me. Probably because many of my repos mention Saddleback College and CS1C.)

You can apply for a student account. This will get you access to private repos for free.
https://help.github.com/articles/applying-for-a-student-developer-pack/

EDIT: Due to issues with past students lying about their education status, you can't just use your Saddleback email address when applying for a student position. You'll need to provide some other proof, like a screenshot of your unofficial transcript. (I do believe you still need to have your actual school email, however.)

**Comment by dacruz21** [comment]
Already discussed with Kath - not an issue
